services:
  # Servidor Web (Nginx / Reveal.js)
  revealjs:
    image: cloudogu/reveal.js
    ports:
      - "8080:8080"
    volumes:
      - ./slides:/reveal/slides
      - ./index.html:/reveal/index.html
      - ./viewer.html:/reveal/viewer.html
      - ./css:/reveal/css

  # Contenedor dedicado al Watcher en Node.js
  watcher:
    image: node:alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: node watch-slides.js
    restart: always
